config/routes.rb
Rails.application.routes.draw do
  
  devise_for :sellers
  resources :books
  root "books#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    has_one_attached :thumbnail
    belongs_to :seller
    belongs_to :category

    # validates :name, :amount, presence: true
    # validates :name, length: { minimum: 0, maximum: 50 }
    # validates :amount, length: { minimum: 0, maximum: 8 }

    before_save :make_it_downcase

    def make_it_downcase
        self.name.downcase!
    end
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :books, dependent: :destroy
end

app/models/seller.rb
class Seller < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    before_action :find_book, only: %i[show edit update destroy]

    def index
        if params.dig(:category).blank? # If there is no category passed in, then it will display all the books
           if params.dig(:query).blank?
                @books = Book.all.order("created_at DESC")
           else
                @books = Book.where("name LIKE (?)", "%#{params.dig(:query).downcase}%")
                redirect_to root_path if @books.empty?
           end
        else
            @category_id = Category.find_by(name: params[:category]).id # Here params[:category] is having the name of the category.
            @books = Book.where(category_id: @category_id)
        end
    end

    def show; end

    def new
        if current_seller.present?
            @book = current_seller.books.new
        else
            redirect_to root_path
        end
    end

    def create
        @book = current_seller.books.new(book_params)
        @book.category_id = params.dig(:book, :category_id)
        if @book.save
            redirect_to root_path
        else
            render 'new'
        end
    end

    def edit; end

    def update
        if @book.update(book_params)
            redirect_to root_path
        else
            render 'edit'
        end
    end

    def destroy
        @book.destroy
        redirect_to root_path
    end

    private

    def find_book
        @book = Book.find(params[:id])
    end

    def book_params
        params.require(:book).permit(:name, :author, :language, :publisher, :date_of_publication, :isbn_10, :description, :amount, :thumbnail, :category_id)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/_form.html.erb
<%= form_with model: @book, local: true do |f| %>

    <div class="mb-3">
        <%= f.collection_select :category_id, Category.all, :id, :name, { include_blank: 'Select a Category *' }, required: true %>
    </div>

    <div class="mb-3">
        <%= f.text_field :name, placeholder: 'Name of the book *', class: "form-control", required: true %>
    </div>

    <div class="mb-3">
        <%= f.text_field :author, placeholder: 'Name of the author *', class: "form-control", required: true %>
    </div>

    <div class="mb-3">
        <%= f.text_field :language, placeholder: 'Language of publication *', class: "form-control", required: true %>
    </div>

    <div class="mb-3">
        <%= f.text_field :publisher, placeholder: 'Publisher *', class: "form-control", required: true %>
    </div>

    <div class="mb-3">
        <label for="formFile" class="form-label">Date of publication *</label>
        <%= f.date_field :date_of_publication, class: "form-control", required: true %>
    </div>

    <div class="mb-3">
        <%= f.text_field :isbn_10, placeholder: 'ISBN-10 *', class: "form-control", required: true %>
    </div>

    <div class="mb-3">
        <%= f.text_area :description, placeholder: 'Description *', class: "form-control", rows: '5', required: true %>
    </div>

    <div class="mb-3">
        <%= f.number_field :amount, placeholder: 'Amount *', class: "form-control", required: true %>
    </div>

    <div class="mb-3">
        <label for="formFile" class="form-label">Select a thumbnail image *</label>
        <%= f.file_field :thumbnail, class: "form-control-file", required: true %>
    </div>

    <div class="mb-3">
        <%= f.submit "Add to the library", class: "btn btn-success" %>
    </div>
<% end %>

app/views/books/edit.html.erb
<h1>Edit the details</h1><br>

<%= render 'form' %>

app/views/books/index.html.erb
<div class = 'row'>
  <% @books.each do |book| %>
    <div class = 'col-md-3 my-auto'>
      <% unless book.thumbnail.nil? %>
        <a href = 'books/<%= book.id %>'>
            <%= image_tag book.thumbnail, class: 'image_thumbnail' %><br>
        </a>
        <h4><br><%= book.amount %></h4>
        <p class = 'small'>
          <% if book.name.length > 16 %>
                <%= book.name.upcase.slice(0..15) + "..." %>
          <% else %>
                <%= book.name.upcase %> 
          <% end %>
        </p>
        
        <br><br>
  
      <% end %>
      
    </div>  
  <% end %>

  <% if @books.empty? %>
    <h3>It seems there are no books in the store! Sign in to add books.</h3>
  <% end %>
</div>

app/views/books/new.html.erb
<h1>Add to the shelf</h1><br>

<%= render 'form' %>

app/views/books/show.html.erb
<div class = 'row'>
    <div class = 'col-md-3'>
        <%= image_tag @book.thumbnail, class: 'main_thumbnail' %>
    </div>
    <div class = 'col-md-6'>
        <h2><strong><%= @book.name.upcase %></strong></h2>
        <p class = 'small'>by <%= @book.author.split(' ').each { |word| word.capitalize! }.join(' ') %></p>
        <br>
        <h4>Rs <%= @book.amount %></h4>
        <br>

        <h6> <%= @book.description %></h6>
        <br>
        <div class = 'row'>
            <div class = 'col-md-3'>
                <i class="fa fa-globe"></i> <%= @book.language.capitalize %>
            </div>
            <div class = 'col-md-3'>
                <i class="fa fa-user"></i> <%= @book.publisher.upcase %>
            </div>
            <div class = 'col-md-3'>
                <i class="fa fa-barcode"></i> <%= @book.isbn_10 %>
            </div>
            <div class = 'col-md-3'>
                <i class="fa fa-calendar"> </i> <%= @book.date_of_publication %>
            </div>
        </div>
    </div><br>
    <div class = 'col'>
        <% if seller_signed_in? %>
            <% if @book.seller_id == current_seller.id %>
                <%= link_to "Delete", book_path(@book.id), class: 'btn btn-danger', method: :delete, data: {confirm: 'Are you sure?'} %>
            <% end %>
        <% end %>

        <%= link_to "Add to Cart", book_path(@book.id), class: 'btn btn-primary' %>
    </div>
</div>

app/views/layouts/_nav.html.erb
<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "The Bibliophile", root_path, class: 'navbar-brand', style: "font-family: 'Nothing You Could Do', cursive; font-size: 25px;" %>
    
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      
      <form class="d-flex">
        <%= form_with url: "/search", method: :get do |form| %>
          <%= form.text_field :query, class: 'form-control me-2', placeholder: 'Search for books...' %>
          <%= button_tag type: 'submit', class: "btn btn-warning", id: "register-button" do %>
            <i class="fa fa-search" aria-hidden="true"></i>
          <% end %>
        <% end %>
      </form>

      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <% if seller_signed_in? %>
            <%= link_to "ADD BOOK", new_book_path, class: 'nav-link active' %>
          <% end %>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link active dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            CATEGORIES
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <% Category.all.each do |category| %>
              <%= link_to category.name, books_path(category: category.name), class: "dropdown-item #{'active' if params[:category] == category.name }" %>
            <% end %><!-- Here the books_path(category: category.name) will pass the category thru the URL -->
          </div>
        </li>
        
          <% if seller_signed_in? %>
            <li class="nav-item">
              <a class="nav-link active disabled" aria-current="page" href="#">Hello, <%= current_seller.email.split('@').first.capitalize %></a>
            </li>
            <%= link_to "Sign Out", destroy_seller_session_path,method: :delete, data: {confirm: 'Do you want to sign out?'}, class: 'nav-link active'%>
          <% else %>
            <%= link_to "Sign In", new_seller_session_path, class: 'nav-link active' %>
          <% end %>
        
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>The Bibliophile</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Nothing+You+Could+Do&family=Poppins:wght@300&display=swap" rel="stylesheet"> 
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/nav' %>

    <div class = "container">
      <%= yield %>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body>
</html>